name: NX CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpx nx affected --target=lint --base=main~1
      - run: pnpx nx affected --target=test --base=main~1
      - run: pnpx nx affected --target=e2e --base=main~1
      - run: pnpx nx affected --target=build --base=main~1
